### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by thejhh** [banksonfi/bankson-js#1]
Probably some require missing from somewhere?

```
/---------------------------------- Error -----------------------------------\
| ReferenceError: Promise is not defined
+---------------------------------- stack -----------------------------------+
|     at Client.beforeRequest (/home/jheusala/scripts/enterpriser/node_modules/bankson-js/lib/client.js:70:14)
|     at Client.headers (/home/jheusala/scripts/enterpriser/node_modules/bankson-js/lib/client.js:89:19)
|     at Client.get (/home/jheusala/scripts/enterpriser/node_modules/bankson-js/lib/client.js:106:19)
|     at InboundPayments.fetch (/home/jheusala/scripts/enterpriser/node_modules/bankson-js/lib/ext/inbound-payments.js:27:24)
|     at /home/jheusala/scripts/enterpriser/bin/update-from-bankson.js:24:32
|     at /home/jheusala/scripts/enterpriser/node_modules/q/q.js:1031:25
| From previous event:
|     at Object.<anonymous> (/home/jheusala/scripts/enterpriser/bin/update-from-bankson.js:12:3)
+-------------------------------- arguments ---------------------------------+
| Promise
+----------------------------------- type -----------------------------------+
| not_defined
\----------------------------------------------------------------------------/
```

I was trying with pretty much the same code as in the docs:

```
var Q = require('q');
var prettified = require('prettified');
var moment = require('moment');
var config = require('../config.js');

Q.fcall(function() {

    var Client = require('bankson-js');

    var client = new Client({
      bearerToken: config.bankson.bearerToken
    });

    var opts = {
        since: moment().subtract(7, 'days').format('YYYY-MM-DD')
    };

    return client.inboundPayments.fetch(opts).then(function(payments) {
        console.log(JSON.stringify(payments, null, 2));
    });

}).fail(function(err) {
    prettified.errors.print(err);
    process.exit(1);
}).done();
```

**Comment by thejhh** [comment]
My Node on this system is still v0.10 though... Probably should upgrade, but there was problems compiling newer Node on this system.

**Comment by thejhh** [comment]
Fixed with `require('es6-promise').polyfill();`
